"""Timestamp columns added

Revision ID: 02364c36e71a
Revises: a60fef7cc402
Create Date: 2026-07-08 11:25:25.991946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02364c36e71a'
down_revision: Union[str, Sequence[str], None] = 'a60fef7cc402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mill_bills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mill_bills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_configuration', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_configuration', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_configuration', 'updated_at')
    op.drop_column('profile_configuration', 'created_at')
    op.drop_column('mill_bills', 'updated_at')
    op.drop_column('mill_bills', 'created_at')
    # ### end Alembic commands ###
