"""-

Revision ID: 024f55c83557
Revises: 06a258810880
Create Date: 2026-07-11 14:26:09.036258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024f55c83557'
down_revision: Union[str, Sequence[str], None] = '06a258810880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_millbill_invoiceNo', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'account', ['last_millbill_invoiceNo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'last_millbill_invoiceNo')
    # ### end Alembic commands ###
