"""add eway bill no. in invoice

Revision ID: 05458ae675a2
Revises: 4a16920d7e2f
Create Date: 2026-07-29 11:13:14.802358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05458ae675a2'
down_revision: Union[str, Sequence[str], None] = '4a16920d7e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Invoices', sa.Column('eway_bill_no', sa.String(length=12), nullable=True))
    op.create_unique_constraint(None, 'session', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_column('Invoices', 'eway_bill_no')
    # ### end Alembic commands ###
