"""-

Revision ID: 060d6bfd3d19
Revises: 75c809d26cc9
Create Date: 2026-07-22 14:18:54.352121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060d6bfd3d19'
down_revision: Union[str, Sequence[str], None] = '75c809d26cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('mill_receipt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'mill_receipt')
    # ### end Alembic commands ###
