"""-

Revision ID: 14b7ee9a4c16
Revises: 
Create Date: 2026-07-11 10:30:13.078557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b7ee9a4c16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mobile_no', sa.String(length=10), nullable=False),
    sa.Column('gstin', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mobile_no ~ '^[0-9]{10}$'", name='ck_users_mobile_no_10_digits'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_gstin'), 'users', ['gstin'], unique=True)
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=True)
    op.create_table('mill_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('seller_address', sa.Text(), nullable=False),
    sa.Column('seller_pan', sa.String(length=10), nullable=False),
    sa.Column('seller_gstin', sa.String(length=15), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('docket_no', sa.String(length=50), nullable=True),
    sa.Column('transport_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_through', sa.String(length=20), nullable=False),
    sa.Column('party_name', sa.String(length=150), nullable=False),
    sa.Column('party_address', sa.Text(), nullable=False),
    sa.Column('party_city', sa.String(length=50), nullable=True),
    sa.Column('party_state', sa.String(length=50), nullable=False),
    sa.Column('party_gstin', sa.String(length=15), nullable=False),
    sa.Column('party_pan', sa.String(length=10), nullable=False),
    sa.Column('seller_bank', sa.String(length=100), nullable=True),
    sa.Column('seller_account', sa.String(length=30), nullable=True),
    sa.Column('seller_ifsc', sa.String(length=11), nullable=True),
    sa.Column('final_taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount_in_words', sa.String(length=500), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.CheckConstraint("trim(delivery_through) <> ''", name='ck_mill_bills_delivery_through_not_blank'),
    sa.CheckConstraint("trim(final_amount_in_words) <> ''", name='ck_mill_bills_final_amount_in_words_not_blank'),
    sa.CheckConstraint("trim(invoice_no) <> ''", name='ck_mill_bills_invoice_no_not_blank'),
    sa.CheckConstraint("trim(party_address) <> ''", name='ck_mill_bills_party_address_not_blank'),
    sa.CheckConstraint("trim(party_gstin) <> ''", name='ck_mill_bills_party_gstin_not_blank'),
    sa.CheckConstraint("trim(party_name) <> ''", name='ck_mill_bills_party_name_not_blank'),
    sa.CheckConstraint("trim(party_pan) <> ''", name='ck_mill_bills_party_pan_not_blank'),
    sa.CheckConstraint("trim(party_state) <> ''", name='ck_mill_bills_party_state_not_blank'),
    sa.CheckConstraint("trim(seller_address) <> ''", name='ck_mill_bills_seller_address_not_blank'),
    sa.CheckConstraint("trim(seller_gstin) <> ''", name='ck_mill_bills_seller_gstin_not_blank'),
    sa.CheckConstraint("trim(seller_name) <> ''", name='ck_mill_bills_seller_name_not_blank'),
    sa.CheckConstraint("trim(seller_pan) <> ''", name='ck_mill_bills_seller_pan_not_blank'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('bill_crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=6), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uqc', sa.String(length=10), nullable=False, min_length=1),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("trim(crop) <> ''", name='ck_bill_crops_crop_not_blank'),
    sa.CheckConstraint("trim(hsn_code) <> ''", name='ck_bill_crops_hsn_code_not_blank'),
    sa.CheckConstraint("trim(uqc) <> ''", name='ck_bill_crops_uqc_not_blank'),
    sa.ForeignKeyConstraint(['bill_id'], ['mill_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_crops')
    op.drop_table('mill_bills')
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.drop_index(op.f('ix_users_gstin'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
