"""mill bill table

Revision ID: 27a3abec3446
Revises: 
Create Date: 2026-07-06 09:45:55.086992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a3abec3446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mill_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('seller_address', sa.Text(), nullable=False),
    sa.Column('seller_pan', sa.String(length=10), nullable=False),
    sa.Column('seller_gstin', sa.String(length=15), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('docket_no', sa.String(length=50), nullable=True),
    sa.Column('transport_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_through', sa.String(length=20), nullable=False),
    sa.Column('party_name', sa.String(length=150), nullable=False),
    sa.Column('party_address', sa.Text(), nullable=False),
    sa.Column('party_city', sa.String(length=50), nullable=True),
    sa.Column('party_state', sa.String(length=50), nullable=False),
    sa.Column('party_gstin', sa.String(length=15), nullable=False),
    sa.Column('party_pan', sa.String(length=10), nullable=False),
    sa.Column('seller_bank', sa.String(length=100), nullable=True),
    sa.Column('seller_account', sa.String(length=30), nullable=True),
    sa.Column('seller_ifsc', sa.String(length=11), nullable=True),
    sa.Column('final_taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('profile_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=6), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uqc', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['mill_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_crops')
    op.drop_table('profile_configuration')
    op.drop_table('mill_bills')
    # ### end Alembic commands ###
