"""Database creation

Revision ID: 4a16920d7e2f
Revises: 
Create Date: 2026-07-28 23:54:09.879741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a16920d7e2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('seller_address', sa.Text(), nullable=False),
    sa.Column('seller_pan', sa.String(length=10), nullable=False),
    sa.Column('seller_gstin', sa.String(length=15), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('docket_no', sa.String(length=50), nullable=True),
    sa.Column('transport_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_through', sa.String(length=20), nullable=False),
    sa.Column('party_name', sa.String(length=150), nullable=False),
    sa.Column('party_address', sa.Text(), nullable=False),
    sa.Column('party_city', sa.String(length=50), nullable=True),
    sa.Column('party_state', sa.String(length=50), nullable=False),
    sa.Column('party_gstin', sa.String(length=15), nullable=False),
    sa.Column('party_pan', sa.String(length=10), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=6), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uqc', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount_in_words', sa.String(length=500), nullable=False),
    sa.Column('seller_bank', sa.String(length=100), nullable=True),
    sa.Column('seller_account', sa.String(length=30), nullable=True),
    sa.Column('seller_ifsc', sa.String(length=11), nullable=True),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.CheckConstraint("trim(crop) <> ''", name='ck_invoices_crop_not_blank'),
    sa.CheckConstraint("trim(delivery_through) <> ''", name='ck_invoices_delivery_through_not_blank'),
    sa.CheckConstraint("trim(final_amount_in_words) <> ''", name='ck_invoices_final_amount_in_words_not_blank'),
    sa.CheckConstraint("trim(hsn_code) <> ''", name='ck_invoices_hsn_code_not_blank'),
    sa.CheckConstraint("trim(invoice_no) <> ''", name='ck_invoices_invoice_no_not_blank'),
    sa.CheckConstraint("trim(party_address) <> ''", name='ck_invoices_party_address_not_blank'),
    sa.CheckConstraint("trim(party_gstin) <> ''", name='ck_invoices_party_gstin_not_blank'),
    sa.CheckConstraint("trim(party_name) <> ''", name='ck_invoices_party_name_not_blank'),
    sa.CheckConstraint("trim(party_pan) <> ''", name='ck_invoices_party_pan_not_blank'),
    sa.CheckConstraint("trim(party_state) <> ''", name='ck_invoices_party_state_not_blank'),
    sa.CheckConstraint("trim(seller_address) <> ''", name='ck_invoices_seller_address_not_blank'),
    sa.CheckConstraint("trim(seller_gstin) <> ''", name='ck_invoices_seller_gstin_not_blank'),
    sa.CheckConstraint("trim(seller_name) <> ''", name='ck_invoices_seller_name_not_blank'),
    sa.CheckConstraint("trim(seller_pan) <> ''", name='ck_invoices_seller_pan_not_blank'),
    sa.CheckConstraint("trim(uqc) <> ''", name='ck_invoices_uqc_not_blank'),
    sa.CheckConstraint('final_amount IS NOT NULL', name='ck_invoices_final_amount_not_null'),
    sa.CheckConstraint('invoice_date IS NOT NULL', name='ck_invoices_invoice_date_not_null'),
    sa.CheckConstraint('qty IS NOT NULL', name='ck_invoices_qty_not_null'),
    sa.CheckConstraint('rate IS NOT NULL', name='ck_invoices_rate_not_null'),
    sa.CheckConstraint('taxable_amount IS NOT NULL', name='ck_invoices_taxable_amount_not_null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_millbill_invoiceNo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_millbill_invoiceNo'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_user_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('trade_creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('party_name', sa.String(length=100), nullable=True),
    sa.Column('party_city', sa.String(length=100), nullable=True),
    sa.Column('party_gstin', sa.String(length=15), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('invoice_crop_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_crop_qty_unit', sa.String(length=10), nullable=True),
    sa.Column('invoice_crop_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_crop_rate_unit', sa.String(length=10), nullable=True),
    sa.Column('vehicle_no', sa.String(length=100), nullable=True),
    sa.Column('mill_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mill_qty_unit', sa.String(length=10), nullable=True),
    sa.Column('mill_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mill_rate_unit', sa.String(length=10), nullable=True),
    sa.Column('gst_collected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tds_deducted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mill_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('farmer_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('labour_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('mill_receipt', sa.String(), nullable=True),
    sa.CheckConstraint("invoice_no IS NULL OR trim(invoice_no) <> ''", name='ck_trades_invoice_no_not_blank'),
    sa.CheckConstraint("mill_qty_unit IS NULL OR trim(mill_qty_unit) <> ''", name='ck_trades_mill_qty_unit_not_blank'),
    sa.CheckConstraint("mill_rate_unit IS NULL OR trim(mill_rate_unit) <> ''", name='ck_trades_mill_rate_unit_not_blank'),
    sa.CheckConstraint("trim(crop_name) <> ''", name='ck_trades_crop_name_not_blank'),
    sa.CheckConstraint('farmer_payment IS NULL OR farmer_payment >= 0', name='ck_trades_farmer_payment_non_negative'),
    sa.CheckConstraint('gst_collected IS NULL OR gst_collected >= 0', name='ck_trades_gst_collected_non_negative'),
    sa.CheckConstraint('labour_cost IS NULL OR labour_cost >= 0', name='ck_trades_labour_cost_non_negative'),
    sa.CheckConstraint('mill_payment IS NULL OR mill_payment >= 0', name='ck_trades_mill_payment_non_negative'),
    sa.CheckConstraint('mill_qty IS NULL OR mill_qty > 0', name='ck_trades_mill_qty_positive'),
    sa.CheckConstraint('mill_rate IS NULL OR mill_rate > 0', name='ck_trades_mill_rate_positive'),
    sa.CheckConstraint('other_cost IS NULL OR other_cost >= 0', name='ck_trades_other_cost_non_negative'),
    sa.CheckConstraint('tds_deducted IS NULL OR tds_deducted >= 0', name='ck_trades_tds_deducted_non_negative'),
    sa.CheckConstraint('transport_cost IS NULL OR transport_cost >= 0', name='ck_trades_transport_cost_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('session')
    op.drop_table('account')
    op.drop_table('Invoices')
    # ### end Alembic commands ###
