"""-

Revision ID: 689bd37a7058
Revises: 66f192559bfb
Create Date: 2026-08-03 19:57:56.392529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689bd37a7058'
down_revision: Union[str, Sequence[str], None] = '66f192559bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Invoices', 'party_pan',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('trades', 'party_city')
    op.drop_column('trades', 'party_gstin')
    op.drop_column('trades', 'invoice_crop_qty_unit')
    op.drop_column('trades', 'invoice_crop_qty')
    op.drop_column('trades', 'invoice_crop_rate')
    op.drop_column('trades', 'invoice_crop_rate_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('invoice_crop_rate_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_qty_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('party_gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('party_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('Invoices', 'party_pan',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
