"""add farmer table

Revision ID: 6e2a0158bf43
Revises: ff3461b87bca
Create Date: 2026-09-28 10:00:38.883602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2a0158bf43'
down_revision: Union[str, Sequence[str], None] = 'ff3461b87bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_farmer_invoiceNo', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'account', ['last_farmer_invoiceNo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'last_farmer_invoiceNo')
    # ### end Alembic commands ###
