"""rcm_tax column add in trade

Revision ID: 742590f9aefd
Revises: 9befdf9a0eba
Create Date: 2026-10-03 22:05:57.424822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742590f9aefd'
down_revision: Union[str, Sequence[str], None] = '9befdf9a0eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('rcm_tax_payment', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'rcm_tax_payment')
    # ### end Alembic commands ###
