"""add trades table

Revision ID: 75c809d26cc9
Revises: a91a5320ff16
Create Date: 2026-07-21 18:06:53.093348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c809d26cc9'
down_revision: Union[str, Sequence[str], None] = 'a91a5320ff16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trade_creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('mill_bill_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('mill_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mill_qty_unit', sa.String(length=10), nullable=False),
    sa.Column('mill_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mill_rate_unit', sa.String(length=10), nullable=False),
    sa.Column('gst_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mill_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('farmer_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("trim(invoice_no) <> ''", name='ck_trades_invoice_no_not_blank'),
    sa.CheckConstraint("trim(mill_qty_unit) <> ''", name='ck_trades_mill_qty_unit_not_blank'),
    sa.CheckConstraint("trim(mill_rate_unit) <> ''", name='ck_trades_mill_rate_unit_not_blank'),
    sa.CheckConstraint('farmer_payment >= 0', name='ck_trades_farmer_payment_non_negative'),
    sa.CheckConstraint('gst_collected >= 0', name='ck_trades_gst_collected_non_negative'),
    sa.CheckConstraint('labour_cost >= 0', name='ck_trades_labour_cost_non_negative'),
    sa.CheckConstraint('mill_payment >= 0', name='ck_trades_mill_payment_non_negative'),
    sa.CheckConstraint('mill_qty > 0', name='ck_trades_mill_qty_positive'),
    sa.CheckConstraint('mill_rate > 0', name='ck_trades_mill_rate_positive'),
    sa.CheckConstraint('other_cost >= 0', name='ck_trades_other_cost_non_negative'),
    sa.CheckConstraint('tds_deducted >= 0', name='ck_trades_tds_deducted_non_negative'),
    sa.CheckConstraint('transport_cost >= 0', name='ck_trades_transport_cost_non_negative'),
    sa.ForeignKeyConstraint(['invoice_no'], ['mill_bills.invoice_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_unique_constraint(None, 'session', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_table('trades')
    # ### end Alembic commands ###
