"""add farmer table

Revision ID: 90d7e7c37a28
Revises: d736c625a658
Create Date: 2026-09-29 12:20:31.190773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d7e7c37a28'
down_revision: Union[str, Sequence[str], None] = 'd736c625a658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FarmerPurchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('merchant_name', sa.String(length=100), nullable=False),
    sa.Column('merchant_address', sa.Text(), nullable=False),
    sa.Column('merchant_gstin', sa.String(length=15), nullable=False),
    sa.Column('farmer_name', sa.String(length=150), nullable=False),
    sa.Column('farmer_address', sa.Text(), nullable=False),
    sa.Column('farmer_village', sa.String(length=50), nullable=True),
    sa.Column('farmer_state', sa.String(length=50), nullable=False),
    sa.Column('farmer_pan', sa.String(length=10), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('uqc', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount_in_words', sa.String(length=500), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.CheckConstraint("document_type IN ('Purchase Bill', 'RCM Purchase Bill', 'Payment Receipt')", name='ck_farmer_purchases_document_type_valid'),
    sa.CheckConstraint("payment_method IN ('Cash', 'NEFT', 'RTGS', 'UPI', 'Cheque', 'Pending')", name='ck_farmer_purchases_payment_method_valid'),
    sa.CheckConstraint("trim(crop) <> ''", name='ck_farmer_purchases_crop_not_blank'),
    sa.CheckConstraint("trim(farmer_name) <> ''", name='ck_farmer_purchases_farmer_name_not_blank'),
    sa.CheckConstraint("trim(final_amount_in_words) <> ''", name='ck_farmer_purchases_final_amount_in_words_not_blank'),
    sa.CheckConstraint("trim(merchant_gstin) <> ''", name='ck_farmer_purchases_merchant_gstin_not_blank'),
    sa.CheckConstraint("trim(merchant_name) <> ''", name='ck_farmer_purchases_merchant_name_not_blank'),
    sa.CheckConstraint("trim(voucher_no) <> ''", name='ck_farmer_purchases_voucher_no_not_blank'),
    sa.CheckConstraint('final_amount IS NOT NULL', name='ck_farmer_purchases_final_amount_not_null'),
    sa.CheckConstraint('qty IS NOT NULL AND qty > 0', name='ck_farmer_purchases_qty_positive'),
    sa.CheckConstraint('rate IS NOT NULL AND rate > 0', name='ck_farmer_purchases_rate_positive'),
    sa.CheckConstraint('voucher_date IS NOT NULL', name='ck_farmer_purchases_voucher_date_not_null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FarmerPurchases')
    # ### end Alembic commands ###
