"""UQC column added in billl

Revision ID: a60fef7cc402
Revises: 27a3abec3446
Create Date: 2026-07-08 00:01:25.618667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60fef7cc402'
down_revision: Union[str, Sequence[str], None] = '27a3abec3446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mill_bills', sa.Column('final_amount_in_words', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mill_bills', 'final_amount_in_words')
    # ### end Alembic commands ###
