"""-

Revision ID: b9192536ede4
Revises: bc245f8d9f11
Create Date: 2026-09-30 08:22:05.925854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9192536ede4'
down_revision: Union[str, Sequence[str], None] = 'bc245f8d9f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('millbill_last_invoice_no', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('account_last_millbill_invoiceNo_key'), 'account', type_='unique')
    op.drop_column('account', 'last_millbill_invoiceNo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_millbill_invoiceNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('account_last_millbill_invoiceNo_key'), 'account', ['last_millbill_invoiceNo'])
    op.drop_column('account', 'millbill_last_invoice_no')
    # ### end Alembic commands ###
