"""trades table edited

Revision ID: bb68595d0c8e
Revises: 060d6bfd3d19
Create Date: 2026-07-27 23:15:02.816992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb68595d0c8e'
down_revision: Union[str, Sequence[str], None] = '060d6bfd3d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('party_name', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('party_city', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('party_gstin', sa.String(length=15), nullable=True))
    op.add_column('trades', sa.Column('crop_name', sa.String(length=100), nullable=True))
    op.execute("UPDATE trades SET crop_name = 'WHEAT' WHERE crop_name IS NULL")
    op.alter_column('trades', 'crop_name', nullable=False)
    op.add_column('trades', sa.Column('invoice_crop_qty', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_qty_unit', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('invoice_crop_rate_unit', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('vehicle_no', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('trades', 'invoice_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('trades', 'mill_qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('trades', 'mill_qty_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('trades', 'mill_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('trades', 'mill_rate_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('trades', 'gst_collected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'tds_deducted',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'mill_payment',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'farmer_payment',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'transport_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'labour_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'other_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_constraint(op.f('trades_invoice_no_fkey'), 'trades', type_='foreignkey')
    op.drop_column('trades', 'mill_bill_pdf_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('mill_bill_pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trades_invoice_no_fkey'), 'trades', 'mill_bills', ['invoice_no'], ['invoice_no'])
    op.alter_column('trades', 'other_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'labour_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'transport_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'farmer_payment',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'mill_payment',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'tds_deducted',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'gst_collected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'mill_rate_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('trades', 'mill_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('trades', 'mill_qty_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('trades', 'mill_qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('trades', 'invoice_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('trades', 'note')
    op.drop_column('trades', 'vehicle_no')
    op.drop_column('trades', 'invoice_crop_rate_unit')
    op.drop_column('trades', 'invoice_crop_rate')
    op.drop_column('trades', 'invoice_crop_qty_unit')
    op.drop_column('trades', 'invoice_crop_qty')
    op.drop_column('trades', 'crop_name')
    op.drop_column('trades', 'party_gstin')
    op.drop_column('trades', 'party_city')
    op.drop_column('trades', 'party_name')
    # ### end Alembic commands ###
