"""-

Revision ID: c96b3b0957e3
Revises: 815e99768398
Create Date: 2026-07-11 12:02:32.577090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96b3b0957e3'
down_revision: Union[str, Sequence[str], None] = '815e99768398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mill_bills', sa.Column('created_by', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('mill_bills_client_id_fkey'), 'mill_bills', type_='foreignkey')
    op.drop_column('mill_bills', 'client_id')
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_gstin'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'mobile_no')
    op.drop_column('users', 'gstin')
    op.drop_column('users', 'business_name')
    op.drop_column('users', 'business_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gstin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mobile_no', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=True)
    op.create_index(op.f('ix_users_gstin'), 'users', ['gstin'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'user_name')
    op.add_column('mill_bills', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mill_bills_client_id_fkey'), 'mill_bills', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mill_bills', 'created_by')
    # ### end Alembic commands ###
